### PR TITLE
Add Enable/Disable Shaders GUI Option and Fix Bugs

### LINKED ISSUE #261: Cannot drag-and-drop directory shaderpacks into the shaderpack GUI
We need to do a recursive copy instead of just copying the folder itself, otherwise we end up with an empty shaderpack directory in the shaderpacks folder, which does not work.

### PR DESCRIPTION
**Pull request by FoundationGames**
Resolves #261, #268, #263
gui_fix_1

### CODE REVIEW

File: src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java [hunk 1]
```diff
@@ -179,6 +181,20 @@ public void filesDragged(List<Path> paths) {
 		this.addedPackDialogTimer = 100;
 	}
 
+	private static void copyShaderPack(Path pack, String name) throws IOException {
+		Path target = Iris.SHADERPACKS_DIRECTORY.resolve(name);
+
+		// Make use of FileUtils to copy a directory with ease.
+		// Needs to convert the NIO Path to an IO File in order to work.
+		if (Files.isDirectory(pack)) {
+			FileUtils.copyDirectory(pack.toFile(), target.toFile());
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java:190]: Not all `Path`s can be converted to `File`s, this should be at the very least checked and noted in a comment.

File: src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java [hunk 2]
```diff
@@ -162,4 +186,38 @@ public void render(MatrixStack matrices, int index, int y, int x, int entryWidth
...
+		public EnableShadersButtonEntry(boolean enabled) {
+			this.enabled = enabled;
+		}
+
+		@Override
+		public void render(MatrixStack matrices, int index, int y, int x, int entryWidth, int entryHeight, int mouseX, int mouseY, boolean hovered, float tickDelta) {
+			GuiUtil.bindTexture(GuiUtil.IRIS_WIDGETS_TEX);
+			RenderSystem.color4f(1.0f, 1.0f, 1.0f, 1.0f);
+			RenderSystem.enableBlend();
+			RenderSystem.enableTexture();
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java:202]: If your goal is to abstract things, these need to be in GuiUtil too. Perhaps this should just be part of drawButton.

File: src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java [hunk 3]
```diff
@@ -30,30 +37,36 @@ public ShaderPackListWidget(MinecraftClient client, int width, int height, int t
...
-			int index = -1;
+			int index = 0;
 
 			for (String pack : BUILTIN_PACKS) {
 				index++;
 				addEntry(index, pack);
 			}
 
-			Collection<Path> folders = Files.walk(path, 1).filter(Iris::isValidShaderpack).collect(Collectors.toList());
+			Collection<Path> folders = Files.walk(path, 1).filter(ShaderPackListWidget::isValidPackPath).collect(Collectors.toList());
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java:69]: Perhaps try https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#list-java.nio.file.Path- instead? Seems like it would solve your problem in a nicer way:

> Some file systems maintain special links to the directory itself and the directory's parent directory. Entries representing these links are not included.

This is also probably relevant in the code for locating the `shaders` directory within a shaderpack.

File: src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java [hunk 4]
```diff
@@ -30,30 +37,36 @@ public ShaderPackListWidget(MinecraftClient client, int width, int height, int t
...
 	}
 
 	@Override
 	protected int getRowTop(int index) {
 		return super.getRowTop(index) + 2;
 	}
 
+	private static boolean isValidPackPath(Path path) {
+		return !path.equals(Iris.SHADERPACKS_DIRECTORY) && Iris.isValidShaderpack(path);
+	}
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java:53]: This should be removed - see my comment on the lines below

File: src/main/java/net/coderbot/iris/gui/GuiUtil.java [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+ * Helps allow for easier portability
+ * to Minecraft 1.17 by abstracting
+ * some code that will be changed.
+ */
+public final class GuiUtil {
+	/**
+	 * Resource ID for the texture used for
+	 * Iris's GUI widgets.
+	 */
+	public static final Identifier IRIS_WIDGETS_TEX = new Identifier("iris", "textures/gui/widgets.png");
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/GuiUtil.java:24]: This should probably just be private, and you can then have a bindWidgetsTexture function in place of bindTexture.

File: src/main/java/net/coderbot/iris/gui/GuiUtil.java [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+		return MinecraftClient.getInstance();
+	}
+
+	/**
+	 * Binds the texture to be used for
+	 * succeeding draw calls.
+	 *
+	 * @param texture The resource ID of the texture to be bound.
+	 */
+	public static void bindTexture(Identifier texture) {
```
Comment (coderbot16) [inline src/main/java/net/coderbot/iris/gui/GuiUtil.java:38]: This should probably be included within drawButton.

**Review by coderbot16 — CHANGES_REQUESTED** [review]
Good improvements, have a few comments though.

File: src/main/java/net/coderbot/iris/gui/GuiUtil.java (hunk 6 above)
Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/GuiUtil.java:38]: There's a specific reason why i didn't call to `bindTexture` directly in `drawButton`, and that is because `drawButton` can also draw a button with the vanilla widgets texture bound to appear like a vanilla button.

File: src/main/java/net/coderbot/iris/gui/GuiUtil.java (hunk 5 above)
Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/GuiUtil.java:24]: Noted, however see my next few responses

File: src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java (hunk 3 above)
Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java:69]: Will be taken care of.

File: src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java (hunk 2 above)
Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/element/ShaderPackListWidget.java:202]: Will do.

File: src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java (hunk 1 above)
Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java:190]: Alright, and I feel like there could be a better, cleaner solution to copying a directory and its contents, so if you know of one let me know

Comment (coderbot16) [reply src/main/java/net/coderbot/iris/gui/screen/ShaderPackScreen.java:190]: I've found a few examples that make use of `Files.walk`, but obviously it wouldn't be a one liner unless we have our own util class. I'm not seeing any one liners in the standard library but maybe I'm not looking hard enough. I wouldn't be opposed to that though, since relying on toFile isn't great, especially when we can be passed arbitrary `Path`s from the OS.

File: src/main/java/net/coderbot/iris/gui/GuiUtil.java (hunk 6 above)
Comment (coderbot16) [reply src/main/java/net/coderbot/iris/gui/GuiUtil.java:38]: Makes sense. I think this is fine as long as the bindWidgetsTexture change is done.

Comment (FoundationGames) [reply src/main/java/net/coderbot/iris/gui/GuiUtil.java:38]: Also I believe this method is going to change in 1.17, and as something used very frequently in GUI code it would be easier to abstract it all so it can be changed quickly when porting

**Comment by FoundationGames** [comment]
Converted to draft due to the discovery of a bug using `Files#list` - `list` does not go further than a depth of 1 when going through files in a directory

**Comment by FoundationGames** [comment]
Bug has been fixed, PR is ready for review once again

**Review by coderbot16 — APPROVED** [review]
Thanks!
